### PR TITLE
Reduce fix u v stride asserts

### PR DESCRIPTION
**Pull request by xnorpx**
I am no expert on this, but at least the encoded stream seems fine reading from a y4m file using the slice.

### CODE REVIEW

**Comment by xnorpx** [comment]
attempt to fix #52

**Comment by ralfbiedert** [comment]
Sorry for delay, on vacation right now, will look at this next week.

**Comment by ralfbiedert** [comment]
Could you add one or more unit tests which check these asserts? You can use `#[should_panic]` for that.

**Comment by xnorpx** [comment]
I will come back and a test for this once time allows.

**Comment by xnorpx** [comment]
Ok added some tests for asserts, been running the slice with y4m crate quite heavily for last couple of weeks so seems to work well.

**Comment by ralfbiedert** [comment]
Thanks!

**Pull request merged**
